application:

  # http服务端口（用于监控脚本运行情况）
  server-port: 8012
  # 文件迁移方式（http、ftp）
  migrate-mode: http
  # 文件上传记录存储介质（boltdb、redis）
  storage-media: boltdb

  # 迁移工作者数组（可同时迁移多个目录）
  workers:
      # 需要进行迁移的源文件目录（两个工作者不能同时迁移一个目录）
    - source-path: ./data
      # 增量迁移文件时间限制（单位：秒，只迁移{migrate-file-time-limit}秒内更新的文件，小于等于0则全部迁移）
      migrate-file-age-limit: 0
      # 定时迁移任务的cron表达式
      job-cron: 0/60 * * * * ?

  # 内置mq
  mq:
    # 内置mq容量大小
    max-size: 10000000
    # 内置mq单批次消费消息数量（必须大于0）
    consume-batch: 100
    # 内置mq消费者数量（文件迁移并发数）
    consumer-num: 10

  # 日志配置
  log:
    # 日志文件最长存活时间（单位：天）
    maxAge: 7