application:

  # http服务接口
  server-port: 8012
  # 文件迁移方式（http、ftp）
  migrate-mode: http
  # 文件上传记录存储介质（boltdb、redis）
  storage-media: boltdb

  # 迁移工作者数组（可同时迁移多个目录）
  workers:
      # 需要进行迁移的源文件目录（两个工作者不能同时迁移一个目录）
    - source-path: ./data
      # 增量迁移文件时间限制（单位：秒，只迁移{migrate-file-time-limit}秒内更新的文件）
      migrate-file-age-limit: 172800
      # 定时迁移任务的cron表达式
      job-cron: 0/30 * * * * ?

  # 内置mq
  mq:
    # 内置mq容量大小
    max-size: 1000
    # 内置mq消费者数量（文件迁移并发数）
    consumer-num: 5