server:
  # 需要进行迁移的源文件目录
  source-path: ./data/fsdata/recordings
  # 增量迁移文件时间限制（单位：秒，只迁移{migrate-file-time-limit}秒内的文件）
  migrate-file-time-limit: 172800
  # 定时迁移任务的cron表达式
  job-cron: 0/10 * * * * ?
  # 内置mq容量大小
  mq-max-size: 1000
  # 文件迁移方式（http、ftp、sftp）
  migrate-mode: http
  # 存储介质（boltdb、redis）
  storage-media: boltdb